version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "c:/postgresql_volume:/var/lib/postgresql/data" #Replace the first directory with its volume. 
      #- "database:/var/lib/postgresql/data" #

  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-server:5.6.9"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "c:/omero_server_volume:/OMERO" #Replace the first directory with its volume.
      #- "omero:/OMERO"

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-web-standalone:5.23.0"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"
    volumes:
      - "c:/omero_web_extension_volume:/opt/omero/web/venv3/lib/python3.6/site-packages/minimal_webapp" #Replace the first directory with its volume.
      - "c:/omero_web_conf_volume/config.omero:/opt/omero/web/config/config.omero" #Replace the first directory with its volume.

  slicer:
    image: "slicer" 
    user: "root"
    environment:
      - "VNC_DISABLE_AUTH=true"
    networks:
      - omero
    ports:
      - "6901:6901"
      - "8085:8085"
    volumes:
      - "c:/slicer_volume:/home/kasm-user/Documents" #Replace the first directory with its volume.
    shm_size: 512m
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      
networks:
  omero:

# volumes:
#   database:
#   omero:
